<?php 
$fichero_reg="   REGEDIT4\n";
$fichero_reg.="\n";
$fichero_reg.="   [HKEY_CURRENT_USER\\Software\\Microsoft\\Internet Account Manager\\Accounts\\".$_GET['usuario']."@".$_GET['dominio']."]\n";
$fichero_reg.="   \"DCEmail\"=dword:00000002\n";
$fichero_reg.="   \"POP3 Server\"=\"mail.".$_GET['dominio']."\"\n";
$fichero_reg.="   \"POP3 Port\"=dword:0000006e\n";
$fichero_reg.="   \"SMTP Server\"=\"mail.".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Port\"=dword:00000019\n";
$fichero_reg.="   \"Connection Type\"=dword:00000001\n";
$fichero_reg.="   \"POP3 User Name\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Display Name\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Email Address\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Reply To Email Address\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Organization Name\"=\"\"\n";
$fichero_reg.="   \"Account Name\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"POP3 Timeout\"=dword:0000003c\n";
$fichero_reg.="   \"SMTP Timeout\"=dword:0000003c\n";
$fichero_reg.="   \"POP3 Secure Connection\"=dword:00000000\n";
$fichero_reg.="   \"Leave Mail On Server\"=dword:00000000\n";
$fichero_reg.="   \"POP3 Skip Account\"=dword:00000000\n";
$fichero_reg.="   \"POP3 Prompt for Password\"=dword:00000000\n";
$fichero_reg.="   \"SMTP User Name\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Use Sicily\"=dword:00000002\n";
$fichero_reg.="   \"SMTP Secure Connection\"=dword:00000000\n";
$fichero_reg.="   \"SMTP Split Messages\"=dword:00000000\n";
$fichero_reg.="   \"SMTP Prompt for Password\"=dword:00000000\n";
$fichero_reg.="\n";
$fichero_reg.="   [HKEY_CURRENT_USER\\Software\\Microsoft\\Office\\Outlook\\OMI Account Manager\\Accounts\\".$_GET['usuario']."@".$_GET['dominio']."]\n";
$fichero_reg.="   \"DCEmail\"=dword:00000002\n";
$fichero_reg.="   \"POP3 Server\"=\"mail.".$_GET['dominio']."\"\n";
$fichero_reg.="   \"POP3 Port\"=dword:0000006e\n";
$fichero_reg.="   \"SMTP Server\"=\"mail.".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Port\"=dword:00000019\n";
$fichero_reg.="   \"Connection Type\"=dword:00000001\n";
$fichero_reg.="   \"POP3 User Name\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Display Name\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Email Address\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Reply To Email Address\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Organization Name\"=\"\"\n";
$fichero_reg.="   \"Account Name\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"POP3 Timeout\"=dword:0000003c\n";
$fichero_reg.="   \"SMTP Timeout\"=dword:0000003c\n";
$fichero_reg.="   \"POP3 Secure Connection\"=dword:00000000\n";
$fichero_reg.="   \"Leave Mail On Server\"=dword:00000000\n";
$fichero_reg.="   \"POP3 Skip Account\"=dword:00000000\n";
$fichero_reg.="   \"POP3 Prompt for Password\"=dword:00000000\n";
$fichero_reg.="   \"SMTP User Name\"=\"".$_GET['usuario']."@".$_GET['dominio']."\"\n";
$fichero_reg.="   \"SMTP Use Sicily\"=dword:00000002\n";
$fichero_reg.="   \"SMTP Secure Connection\"=dword:00000000\n";
$fichero_reg.="   \"SMTP Split Messages\"=dword:00000000\n";
$fichero_reg.="   \"SMTP Prompt for Password\"=dword:00000000\n";

$file_nombre="email.reg";
 header("Content-Type: application/force-download");
 header("Content-Type: application/octet-stream");
 header("Content-Type: application/download");
 header("Content-Disposition: attachment; filename=$file_nombre");
 header("Content-Transfer-Encoding: binary");
 echo $fichero_reg;
?>